//SESSION
export const CHECK_SESSION = "[AUTH] CHECK_SESSION";
//USER DATA
export const GET_USER_DATA = "[AUTH] GET_USER_DATA";
export const RECIEVE_USER_DATA = "[AUTH] RECIEVE_USER_DATA";

//*
export const GET_USER_DATA_FAILED = "[AUTH] GET_USER_DATA_FAILED";

//AUTHENTICATION
export const HANDLE_AUTHENTICATION = "[AUTH] HANDLE_AUTHENTICATION";
export const AUTH_SUCCESS = "[AUTH] AUTH_SUCCESS";
export const AUTH_FAILED = "[AUTH] AUTH_FAILED";

//REGISTRATION
export const HANDLE_REGISTRATION = "[REGISTRATION] HANDLE_REGISTRATION";
export const REGISTRATION_SUCCESS = "[REGISTRATION] REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "[REGISTRATION] REGISTRATION_FAILED";
export const OPEN_REGISTRATION_MODAL = "[UI] OPEN_REGISTRATION_MODAL";
export const CLOSE_REGISTRATION_MODAL = "[UI] CLOSE_REGISTRATION_MODAL";

//SIDEBAR
export const SIDER_OPEN = "[UI] SIDER_OPEN";
export const SIDER_CLOSE = "[UI] SIDER_CLOSE";

//LOADER
export const START_LOADING = "[UI] START_LOADING";
export const STOP_LOADING = "[UI] STOP_LOADING";

//LOGOUT
export const HANDLE_LOGOUT = "[AUTH] HANDLE_LOGOUT";
export const LOGOUT_SUCESS = "[AUTH] LOGOUT_SUCESS";
export const LOGOUT_FAILED = "[AUTH] LOGOUT_FAILED";

//GET ITEMS
export const GET_ITEMS = "[DATA] GET_ITEMS";
export const RECIEVE_ITEMS = "[DATA] RECIEVE_ITEMS";
export const GET_ITEMS_FAILED = "[DATA] GET_ITEMS_FAILED";

//REMOVE ITEM
export const REMOVE_ITEM = "[DATA] REMOVE_ITEM";

///zavristi ovoo
export const REMOVE_ITEM_SUCCESS = "[DATA] REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_FAILED = "[DATA] REMOVE_ITEM_FAILED";

//SELECT ITEM
export const SELECT_ITEM = "[DATA] SELECT_ITEM";

//ADD PRODUCT
export const OPEN_ADD_PRODUCT_MODAL = "[UI] OPEN_ADD_PRODUCT_MODAL";
export const PUSH_CATEGORY = "[DATA] PUSH_CATEGORY";
export const PUSH_BASIC_INFO = "[DATA] PUSH_BASIC_INFO";
export const PRODUCT_ADDING = "[DATA] PRODUCT_ADDING";
export const PRODUCT_ADDING_SUCESS = "[DATA] PRODUCT_ADDED_SUCESS";
export const PRODUCT_ADDING_FAILED = "[DATA] PRODUCT_ADDING_FAILED";
export const NEXT_STEP = "[UI] NEXT_STEP";
export const PREV_STEP = "[UI] PREV_STEP";
export const CANCEL_ADD_PRODUCT = "[DATA] CANCEL_ADD_PRODUCT";
export const CLOSE_ADD_PRODUCT_MODAL = "[UI] CLOSE_ADD_PRODUCT_MODAL";

//EDIT PRODUCT
export const OPEN_EDIT_PRODUCT_MODAL = "[UI] OPEN_EDIT_PRODUCT_MODAL";
export const CLOSE_EDIT_PRODUCT_MODAL = "[UI] CLOSE_EDIT_PRODUCT_MODAL";

//PRODUCT INFO
export const OPEN_PRODUCT_INFO_DRAWER = "[UI] OPEN_PRODUCT_INFO_DRAWER";
export const CLOSE_PRODUCT_INFO_DRAWER = "[UI] CLOSE_PRODUCT_INFO_DRAWER";

//MESSAGES
export const NEW_MESSAGE_MODAL_OPEN = "[UI] NEW_MESSAGE_MODAL_OPEN";
export const NEW_MESSAGE = "[WEBSOCKET] NEW_MESSAGE";
export const SELECT_MESSAGE = "[DATA] SELECT_MESSAGE";
export const UPDATE_MESSENGER = "[DATA] UPDATE_MESSENGER";
export const NEW_MESSAGE_MODAL_CLOSE = "[UI] NEW_MESSAGE_MODAL_CLOSE";

//CONNECTIONS
export const GET_CONNECTIONS = "[DATA] GET_CONNECTIONS";
export const RECIEVE_CONNECTIONS = "[DATA] RECIEVE_CONNECTIONS";
export const UPDATE_MESSAGES = "[DATA] UPDATE_MESSAGES";

//ORDERS
export const GET_ORDERS = "[DATA] GET_ORDERS";
export const RECIEVE_ORDERS = "[DATA] RECIEVE_ORDERS";
//WEBSOCKET
export const START_CHANNEL = "[WEBSOCKET] START_CHANNEL";
export const STOP_CHANNEL = "[WEBSOCKET] STOP_CHANNEL";
export const CHANNEL_ON = "[WEBSOCKET] CHANNEL_ON";
export const CHANNEL_OFF = "[WEBSOCKET] CHANNEL_OFF";
export const SERVER_ON = "[WEBSOCKET] SERVER_ON";
export const SERVER_OFF = "[WEBSOCKET] SERVER_OFF";
export const SEND_MESSAGE = "[WEBSOCKET] SEND_MESSAGE";
